name: build-static-libcec-unix
description: Builds static libcec on Unix environments.

inputs:
  build_type:
    description: The build type, either "release" or "debug".
    required: true

outputs:
  binary_path:
    description: The freshly-built binary path.
    value: ${{ steps.set_output.outputs.binary_path }}

runs:
  using: composite
  steps:
    - name: Checkout upstream libcec 6.0.2
      uses: actions/checkout@v4
      with:
        path: libcec
        submodules: recursive
 
    - name: Install libudev-dev & pkg-config as libcec build dependencies
      run: sudo apt-get install -yq libudev-dev pkg-config
      shell: bash

    - name: Build libcec
      shell: bash
      run: $GITHUB_ACTION_PATH/build.sh '${{ github.workspace }}/libcec' '${{ matrix.build_type }}'

    - name: Set output
      id: set_output
      shell: bash
      run: echo "binary_path=${{ github.workspace }}/libcec/dist" >> $GITHUB_OUTPUT
